### ISSUE TITLE
Don't request articles more than once

### ISSUE THREAD

**Issue by ConnorFoody** [opinionated/scraper-core#3]
Probably should be done in the RSSSchedulable when it builds a list of articles to request. Can just use a list of previously found articles, not a DB, if they don't add, remove then re-add articles to the RSS (should check this when building DB)

**Comment by ConnorFoody** [comment]
needs testing, but should be fixed

**Comment by austindoeswork** [comment]
i can do this this week

**Comment by ConnorFoody** [comment]
Ok, you should mock the scheduler when running this

**Comment by ConnorFoody** [comment]
Has this been tested?

**Comment by ConnorFoody** [comment]
done
